nmchallenge/force-app/main/default/objects/Asset/fields/RequestId__c.field-meta.xml
<CustomField>
    <fullName>RequestId__c</fullName>
    <displayFormat>REQ-{00000}</displayFormat>
    <externalId>true</externalId>
    <label>RequestId</label>
    <type>AutoNumber</type>
</CustomField>

nmchallenge/force-app/main/default/objects/OpportunityLineItem/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Asset</relationshipName>
    <type>Lookup</type>
</CustomField>

nmchallenge/force-app/main/default/classes/Asset_Helper.cls
/**
 * @Author: Eduardo Trujillo
 * 
 */ 
public class Asset_Helper {
	public static void newAsset(Opportunity opp) {
        List<OpportunityLineItem> oliL = [select id, Product2.Name from OpportunityLineItem where OpportunityId = :opp.Id];
        Id c = [select Account.PersonContactId from Opportunity where id = :opp.Id][0].Account.PersonContactId;
        for (OpportunityLineItem oli: oliL) {
            Asset ass = new Asset();
            ass.Name = 'Request: '+oli.Product2.Name +' for: ' +opp.Name;
            ass.Opportunity__c = opp.Id;
            ass.AccountId = opp.AccountId;
            ass.Product2Id = oli.Product2Id;
            insert ass;
            Task t = new Task();
            t.Subject = ass.RequestId__c;
            t.OwnerId = opp.OwnerId;
            t.Status = 'In Progress';
            t.WhatId = ass.Id;
            t.WhoId = c;
            t.Type = 'Asset Order';
            insert t;
            oli.Asset__c = ass.Id;
            update oli;
        }
    }
}